// Previously published posts retired on May 25 and September 6, 2026.
// Keep exact paths: a wildcard would also capture current and future articles.
// These are the closest maintained destinations, not equivalent replacements
// for every retired review or tutorial. Do not promise transferred rankings.
const groups = [
  {
    destination: "/ai-consulting",
    slugs: [
      "ai-automation-audit",
      "business-automation-guide",
      "claude-ai-review",
      "claude-vs-chatgpt",
      "go-high-level-review",
      "go-high-level-vs-activecampaign",
      "go-high-level-vs-hubspot",
      "gohighlevel-free-trial",
      "gohighlevel-pricing",
      "gohighlevel-vs-clickfunnels",
      "gohighlevel-vs-salesforce",
      "hermes-ai-vs-chatgpt",
      "kartra-pricing",
      "kartra-vs-clickfunnels",
      "kartra-vs-gohighlevel",
      "kartra-vs-kajabi",
      "make-com-pricing",
      "make-vs-zapier",
      "ontraport-pricing",
      "ontraport-review",
      "ontraport-vs-gohighlevel",
      "openai-pricing",
      "what-is-agi",
      "what-is-gohighlevel",
      "what-is-hermes-ai",
      "what-is-n8n",
      "zapier-pricing-guide",
      "zapier-review",
    ],
  },
  {
    destination: "/ai-implementation",
    slugs: [
      "ai-automation-workflows-2025",
      "chatgpt-api-guide",
      "chatgpt-for-business",
      "claude-code-automation-business",
      "claude-code-hooks-guide",
      "claude-mcp-guide",
      "custom-gpts-for-business",
      "gohighlevel-automation-workflows",
      "gohighlevel-calendar-setup",
      "gohighlevel-crm-tutorial",
      "gohighlevel-email-marketing",
      "gohighlevel-for-agencies",
      "gohighlevel-for-local-business",
      "gohighlevel-lead-source-tracking",
      "gohighlevel-missed-call-text-back",
      "gohighlevel-saas-mode",
      "kartra-email-marketing",
      "kartra-landing-page-builder",
      "kartra-membership-sites-guide",
      "make-com-tutorial-for-beginners",
      "make-data-stores-guide",
      "make-error-handling-reliable-automations",
      "make-webhooks-guide",
      "n8n-error-handling-workflow-recovery",
      "n8n-queue-mode-scaling",
      "n8n-self-hosted-setup",
      "n8n-webhook-security",
      "ontraport-campaign-automation",
      "ontraport-forms-lead-capture-guide",
      "ontraport-lead-scoring",
      "openai-responses-api-guide",
      "small-business-workflow-automation",
      "zapier-paths-guide",
      "zapier-tables-guide",
    ],
  },
  {
    destination: "/agent-teams",
    slugs: [
      "ai-agents-vs-traditional-automation",
      "automated-lead-followup-system",
      "gohighlevel-ai-agents",
      "n8n-ai-agent-workflows",
      "zapier-agents-guide",
    ],
  },
  {
    destination: "/blog/team-knowledge-ai-workflows",
    slugs: [
      "business-process-documentation-for-automation",
      "human-in-the-loop-automation",
    ],
  },
  {
    destination: "/blog/hermes-agent-skills-guide",
    slugs: [
      "hermes-agent-business-automation",
      "hermes-agent-cron-jobs",
    ],
  },
];

export const legacyBlogRedirects = groups.flatMap(({ destination, slugs }) =>
  slugs.map((slug) => ({
    source: `/blog/${slug}`,
    destination,
    permanent: true as const,
  })),
);
